[INFRA] Fix Scala 2.13 build on JDK 8 by using release 8 instead of 1.8 (#11784)
Fix build error under JDK 8 and Scala 2.13:

[ERROR] scalac error: '1.8' is not a valid choice for '-release'
[INFO]   scalac -help  gives more information
[ERROR] scalac error: bad option: '-release:1.8'
[INFO]   scalac -help  gives more information
[ERROR] exception compilation error occurred!!!
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)